repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
    - id: forbid-tabs
    - id: remove-tabs
      args: [--whitespaces-count, '4']
    - id: chmod
      args: ['644']
      files: \.md$

-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black
        args: [--safe]

-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.9.0'
    hooks:
    -   id: mypy

-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/adamchainz/django-upgrade
    rev: '1.16.0'
    hooks:
    -   id: django-upgrade
        args: ['--target-version', '4.2']

# Run the Ruff linter.
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
    # Linter
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]

-   repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.34.1
    hooks:
    -   id: djlint-reformat-django
    -   id: djlint-django
